# Homework-1-Question-1-Regression-Tree
This repository will take you through the steps in R and the output associated with the Regression Tree Question.
library(foreign)
calif <- read.table("http://www.stat.cmu.edu/~cshalizi/350/hw/06/cadata.dat", header=TRUE)
install.packages("tree")
library(tree)
require(tree)
library(ggplot2)
install.packages("stargazer")
library(stargazer)
install.packages("knitr")
library(knitr)
install.packages("rpart")
require(rpart)
library(rpart)
install.packages("randomForest")
library(randomForest)
install.packages("mice")
library(mice)
install.packages("ROCR")
library(ROCR)
treefit = tree(log(MedianHouseValue) ~ Longitude+Latitude,data=calif)
plot(treefit)
text(treefit,cex=0.75)
price.deciles = quantile(calif$MedianHouseValue,0:10/10)
cut.prices = cut(calif$MedianHouseValue,price.deciles,include.lowest=TRUE)
plot(calif$Longitude,calif$Latitude,col=grey(10:2/11)[cut.prices],pch=20,xlab="Longitude",ylab="Latitude",main="Map of Median House Prices in California",sub="(Darker Areas Are More expensive)")
install.packages("partition.tree")
partition.tree(treefit,ordvars=c("Longitude","Latitude"),add=TRUE)
summary(treefit)
treefit3 <- tree(log(MedianHouseValue) ~., data=calif)
plot(calif$Longitude,calif$Latitude,col=grey(10:2/11)[cut.prices],pch=20,xlab="Longitude",ylab="Latitude")
treefit2 <- tree(log(MedianHouseValue) ~ Longitude + Latitude,data=calif,mindev=.001)
partition.tree(treefit2,ordvars=c("Longitude","Latitude"),add=TRUE,cex=0.3)
plot(treefit3)
text(treefit3,cex=0.5,digits=3)
cut.predictions = cut(predict(treefit3),log(price.deciles),include.lowest=TRUE)
plot(calif$Longitude,calif$Latitude,col=grey(10:2/11)[cut.predictions],pch=20,xlab="Longitude",ylab="Latitude")

